version: '3'
services:
  react-app:
    container_name: vite-react-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    ports:
      - "80:80"
    volumes:
      - .:/app/src
      - /node_modules
    stdin_open: true
    tty: true
    restart: unless-stopped
    environment:
      - CHOKIDAR_USEPOLLING=true


# version: '3'
# services:
#   react-app:
#     container_name: vite-react-app
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "3000:3000"
#     volumes:
#       - .:/app
#       - /app/node_modules
#     stdin_open: true
#     tty: true
#     restart: unless-stopped
